### ISSUE TITLE
Open error: Error Domain=LzmaSDKObjCReader Code=-1 "Can't create archive object file type: 1" UserInfo={code=-1, NSLocalizedDescription=Can't create archive object file type: 1, file=/Users/kjx/XHWorkStation/XHEnglishBrushStudent/Pods/LzmaSDK-ObjC/src/LzmaSDKObjCFileDecoder.cpp, line=185}

### ISSUE THREAD

**Issue by codesourse** [OlehKulykov/LzmaSDKObjC#10]
Open error: Error Domain=LzmaSDKObjCReader Code=-1 "Can't create archive object file type: 1" UserInfo={code=-1, NSLocalizedDescription=Can't create archive object file type: 1, file=/Users/kjx/XHWorkStation/XHEnglishBrushStudent/Pods/LzmaSDK-ObjC/src/LzmaSDKObjCFileDecoder.cpp, line=185}

**Comment by codesourse** [comment]
[!] Unable to satisfy the following requirements:

- `LzmaSDK-ObjC (~> 1.1.4)` required by `Podfile`

Specs satisfying the `LzmaSDK-ObjC (~> 1.1.4)` dependency were found, but they required a higher minimum deployment target.

**Comment by dhcarmona** [comment]
I'm facing the same issue. Compiling for minimal target 10.9, this library doesn't seem to be able to handle 7z files. I get:

LZMA DEBUG 80: ERROR: code = -1, file = ...../LzmaSDK-ObjC/src/LzmaSDKObjCFileDecoder.cpp', line = 185, description = Can't create archive object file type: 1

**Comment by OlehKulykov** [comment]
Hi, this happens when available codec can't be found in a case of static linking. Use frameworks, e.g. dynamic linking to avoid stripping codec code withing final binary.
