### ISSUE TITLE
7z archive creation support?

### ISSUE THREAD

**Issue by tconkling** [OlehKulykov/LzmaSDKObjC#11]
Howdy - I see that support for creating and updating 7z archives is on your roadmap. Curious if there's an ETA for this functionality?

Thanks!

**Comment by OlehKulykov** [comment]
Hi, for now there is only compressing functionality of single buffer object with Lzma2.

**Comment by OlehKulykov** [comment]
Since ver. 2.0.2 you can create 7z archives with Lzma or Lzma2 methods.

**Comment by tconkling** [comment]
Awesome! Thanks for adding this.
