### ISSUE TITLE
Compress file in iOS and decompress in Java

### ISSUE THREAD

**Issue by S4TNEW** [OlehKulykov/LzmaSDKObjC#12]
Hi, I want to transfer a file from an Ipad to an Java web application.

In iOS I use the LzmaSDKObjCBufferCompressLZMA2 to compress the file content:
>
if let data = NSData(contentsOfFile: pathToFile)
{
    if let compress = LzmaSDKObjCBufferCompressLZMA2(data, 0)
    {
        compress.writeToFile(backupPath, atomically: true)
    }
}

But on server side neither decompressor (XZ utils, Apache Commons Compressor) is able to detect the file content as valid format.

So my question is: What do I have to do in order to save a valid LZMA(2) compressed file that can be decompressed by those libraries?

**Comment by OlehKulykov** [comment]
Hi, this method compress raw buffer data and output is LZMA2 compressed data object. But not .7z file content. 
Creating and Editing 7z files is in TODO list on a main page.

If you need to detect your compressed buffer data as file, you need to add header before and/or footer after compressed data. For example you could add tar header.

**Comment by OlehKulykov** [comment]
Since ver. 2.0.2 you can create 7z archives with Lzma or Lzma2 methods.
