### ISSUE TITLE
Архив с папками не распаковывается вовсе или частично.

### ISSUE THREAD

**Issue by DimonDeveloper** [OlehKulykov/LzmaSDKObjC#2]
BOOL Done = [reader extract:items toPath:destionation withFullPaths:YES];

Done всегда NO; и ничего не распаковывает.

Если withFullPaths:NO то Done тоже NO, при этом распаковывает, но все файлы из папок кидает в одну.

Тестил на этом файле
http://files.d-lan.dp.ua/download.php?file=a2b9d437ea26b638e7b2b7df99e1cf8f

**Comment by OlehKulykov** [comment]
Да, застревает при создании/пересоздании файла в несуществующей директории.
Что касается ```withFullPaths:NO``` - то это упрощенный режим, который изначально и требовался, не важно.
Что касается ```withFullPaths:YES``` - добавлен функционал создания дерева каталогов для распаковки.

**Comment by DimonDeveloper** [comment]
Было бы здорово исправить эти warnings.
![screen shot 2015-11-23 at 3 24 42 pm](https://cloud.githubusercontent.com/assets/3527457/11337531/60dd8b94-91f6-11e5-8754-8b4d17519e52.png)

Еще хорошо бы сделать метод который проверяет битый файл или нет.
Ну и поддержку других форматов (в частности bzip, tar(и его вариации)) если это всё уместно конечно.

**Comment by OlehKulykov** [comment]
Данный тестовый файл `example.7Z` 2 из 3х десктопных mac программ не смотли полностью распаковать. Какой программой архиватором пользовались при создании тестового файла `example.7Z`, какая версия LZMA ?
Сдесь используется версия 15.06 и в последней версии cocoapod (0.0.7) удалось полностью распаковать.
Что касается `warnings` - то подключите этот pod как ```pod 'LzmaSDK-ObjC', :inhibit_warnings => true ``` .
По поводу теста - то сдесь все просто - в C++ реализации и без того происходит проверка CRC и финального размера данных на выходе. Потому просто раскомменчена обработка всех состояний распаковки одиночного файла и ради теста пишется в пустой стрим.

А вот по поводу других форматов - то это не планируется, т.к. это не программа архиватор как у 7zip'a. Для других форматов явно хватает и других, лучших реализаций, не таких хардкорных как LZMA с её, `гвоздями прибитостостью` к винде и невозможностью нормально портировать, поддерживать, версионить и патчить. От сюда и все проблемы и куча модификаций на основе одной из версий кода.......

**Comment by DimonDeveloper** [comment]
Для архивации пробовал Entropy, Archiver и Archive Expert. 
Сделал пару тестов и нашел кое что, архивы с папками распаковываются, но не все, дерева каталогов из папок  a -> b распаковываются, но если будит a -> b -> c то уже нет.

И ещё заметил что если в архиве есть пустые папки, то они не распаковываются даже если в них есть другие пустые папки.

https://www.dropbox.com/s/f2vqgw1263x4f3m/Archive.7z?dl=0 - архив с двумя папками и файлами внутри них, распаковывается отлично.

https://www.dropbox.com/s/swzuoi8cw1p16ji/a.7z?dl=0 - тот же архив, но теперь в корневой папке "untitled folder" есть другая папка "1" с файлом . Вот тут и перестаёт распаковывать.

**Comment by DimonDeveloper** [comment]
Обновите cocoapods пожалуйста.

**Comment by OlehKulykov** [comment]
use_frameworks!
platform :ios, '8.0'

pod 'LzmaSDKObjC', :inhibit_warnings => true
