### ISSUE TITLE
Encrypt and decrypt in memory

### ISSUE THREAD

**Issue by own2pwn** [OlehKulykov/LzmaSDKObjC#21]
Привет! Спасибо за библиотеку. Есть вопрос: как можно реализовать сжатие и экстракт сразу в память? Т.е. хочется использовать что-то по типу 
`LzmaSDKObjCWriter * writer = [[LzmaSDKObjCWriter alloc] initWithBuffer: ]];`
Чтобы я мог указать степень сжатия и шифрование контента

**Comment by OlehKulykov** [comment]
Привет. Нужно добавлять RAM/memory стримы по типу LzmaSDKObjC::OutFile и LzmaSDKObjC::InFile с той разницей, что писать и читать нужно из/в RAM.

1. Для записи архива в RAM стрим/файл менять нужно сдесь:
LzmaSDKObjCFileEncoder.{h/cpp}
bool FileEncoder::openFile(const char * path)

2.1. Для распаковки архива из RAM стрима/файла, менять сдесь:
LzmaSDKObjCFileDecoder.{h/cpp}
bool FileDecoder::openFile(const char * path)

2.2. Для распаковки архива в отдельные RAM стримы/файлы, менять сдесь:
LzmaSDKObjCExtractCallback.mm
ExtractCallback::getExtractStream
