### ISSUE TITLE
Being unable to install in a objc project, no swift inside.

### ISSUE THREAD

**Issue by tererecool** [OlehKulykov/LzmaSDKObjC#26]
I am being unable to add this SDK to my project, I added the pod and run pod install but when trying to call `reader open` I am getting following warning in the console:

> LZMA DEBUG 85: ERROR REASON: - Unsupported archive GUID.
> - Codec was not compiled in or stripped by static linking. Make sure you are using 'use_frameworks!' and/or dynamic linking.

Is there anything else than only adding the pod necessary to be able to run this? I am also not sure about following line in the documentation about "Installation":

> Use frameworks (dynamic linking) to include Lzma codecs code in your application.

Does this mean that use_frameworks! MUST be added to the pod file in order for this SDK to work?

**Comment by tererecool** [comment]
For others that may read this, the only way to make this pod work was by using use_frameworks! that meant A LOT of changes in my whole project until it compiled.

**Comment by tyy** [comment]
have u fix this issue?
