### ISSUE TITLE
Feature request: function to uncompress only one file

### ISSUE THREAD

**Issue by tererecool** [OlehKulykov/LzmaSDKObjC#27]
Currently it is only possivble no uncompress the whole file, but that is not really enough for a productive app, uncompressing single files inside the 7z should be possible.

**Comment by OlehKulykov** [comment]
Not currently and not previously. 
Use _iterateWithHandler_ to filter/get required file item.
See _Readme.md_ section "_Iterate archive items, select and store required items for future processing_"

**Comment by tererecool** [comment]
But having LzmaSDKObjCItem does not help as this class does not have a function to uncompress. My use case is a file explorer, I open the compressed file using the iterator and show the list of files, that's working fine, but then I want to be able to open one of the files being shown, how do I achieve that with this lib?
WIth the lib OZZipFile for zip files it works using following code:

OZZipFile *unzipFile= [[OZZipFile alloc] initWithFileName:_zipRootPath mode:OZZipFileModeUnzip];
[unzipFile locateFileInZip:fileInfo.providerPath];
OZZipReadStream *read= [unzipFile readCurrentFileInZip];
NSMutableData *data= [[NSMutableData alloc] initWithLength:4000];
NSUInteger bytesRead= [read readDataWithBuffer:data];
...

I don't have idea how to achieve something like that with this lib.
