### ISSUE TITLE
"No suitable decoder found."

### ISSUE THREAD

**Issue by skauthner** [OlehKulykov/LzmaSDKObjC#3]
Using the sample code, with a valid .7z file, I get the message:

Open error: Error Domain=LzmaSDKObjCReader Code=-1 "No suitable decoder found."

Running on iOS 9.1, Xcode 7.1.1.

Seems to be because CreateObject is not returning S_OK, I couldn't get further than this though?

**Comment by OlehKulykov** [comment]
1. Check file path path exists.
2. Check path extension for correct detecting archive type, because need to create suitable decoder, plus to all, file can be encrypted.

Or create reader with predefined archive type:
```c
- (nonnull id) initWithFileURL:(nonnull NSURL *) fileURL andType:(LzmaSDKObjCFileType) type
```

Also, since release 0.0.6 was added initial error processing.

**Comment by skauthner** [comment]
Thanks, I'm using  -initWithFileURL:andType: Also, the file does exist

It looks like the function RegisterArc() is not called to register a decoder for 7z- I don't know why though.

I also tried the sample project (i.e. 'pod try LzmaSDK-ObjC'), and it worked fine. But then I copied and pasted the sample code into my own project (ViewController.h/.m) and got the 'No suitable decoder error'. Same code, and as far as I can tell, same build settings?

**Comment by OlehKulykov** [comment]
Yes, problem in stripping big half of c++ code without initializing static vars.
Solution found - make framework, add them to embeded frameworks list.
If it's time critical for you, you could build and link manually. Build command: ```xcodebuild -configuration Release -project ios.xcodeproj -target MakeLzmaSDKObjCFramework -sdk iphoneos9.1 clean build ``` than add universal ```LzmaSDKObjC.framework``` to the embeded frameworks.
![screen shot](https://cloud.githubusercontent.com/assets/2852710/11438357/9f70f3f4-94f4-11e5-9ee2-8e26d22e5226.png)
Next step - make this automatically.

**Comment by OlehKulykov** [comment]
Hello, created cocoapod with dynamic framework, you could use it.
```
use_frameworks!
platform :ios, '8.0'

pod 'LzmaSDKObjC', :inhibit_warnings => true
```

**Comment by skauthner** [comment]
Awesome, thanks, I'll give this a try!
