### ISSUE TITLE
Extraction of one item in continuous archive leads to extraction of all items

### ISSUE THREAD

**Issue by sndstudio** [OlehKulykov/LzmaSDKObjC#30]
Привет! Большое спасибо за библиотеку. Столкнулся со следующей проблемой:
пытаюсь распаковать один файл в непрерывном архиве, но в результате получаю не только этот файл, но и все те, которые находились перед ним.

Мой код:
```
    NSURL *url = [NSURL fileURLWithPath:@"/Users/Admin/Desktop/1.7z"];
    LzmaSDKObjCReader *lzmaArch = [[LzmaSDKObjCReader alloc] initWithFileURL:url];
    if (![lzmaArch open:nil])
        return;
    
    __block NSError *iterateError;
    NSMutableArray *items = [[NSMutableArray alloc] init];
    [lzmaArch iterateWithHandler:^BOOL(LzmaSDKObjCItem * item, NSError *error)
     {
         if (error)
             iterateError = error;
         
         [items addObject:item];
         return error == nil;
     }];
    
    if (iterateError)
        return;
    
    // извлекаем только 5й LzmaSDKObjCItem, но по факту извлекутся первые 5
    [lzmaArch extract:@[items[4]] toPath:@"/Users/Admin/Desktop" withFullPaths:NO];
```

Проблемный файл пришлось дополнительно запаковать в zip, так как Github не поддерживает прикрепление .7z
[1.7z.zip](https://github.com/OlehKulykov/LzmaSDKObjC/files/1272819/1.7z.zip)

С обычными архивами таких проблем, разумеется, нет - извлекает только указанный item.

**Comment by OlehKulykov** [comment]
Привет, вы первый кто добавил тестовый файл, спасибо. Проблема найдена и будет решена в ближайшие дни.

**Comment by sndstudio** [comment]
Большое спасибо, жду!

**Comment by pascalsimplice** [comment]
Thank you very much!!!
I had the same problem.
I am looking forward to this fix.

**Comment by OlehKulykov** [comment]
Hi, you could try latest version 2.0.17.

**Comment by pascalsimplice** [comment]
Hello,
I tried and it worked perfectly.
Thank you for the quick update.
This is brilliant work.
