### ISSUE TITLE
Extract zip data from nsdata 

### ISSUE THREAD

**Issue by sswain2** [OlehKulykov/LzmaSDKObjC#36]
Hello ,

I have a base64 string which I am converting to nsdata and that nsdata is in 7zip format , I want to decompress the data using LzmaSDKObjCBufferDecompressLZMA2 function but I am not able to decompress it . my result is always 0 bytes .

can you point me to correct direction

**Comment by sswain2** [comment]
hi,

I have one more concern regarding this matter 

LzmaSDKObjCBufferDecompressLZMA2 is only taking the byte for which I am getting only the first byte , if I can pass the entire nsdata to byte array and then to the method LzmaSDKObjCBufferDecompressLZMA2.

is it possible ?please help me in this matter .

**Comment by OlehKulykov** [comment]
Hi, as you wrote "nsdata is in 7zip format" this means that your data is archive file. In this case you should store you buffer to file and use reader(seams like it's your case).

But, if you are sure that the buffer you have is compressed buffer with lzma2 algorithm and the buffer contains first byte with properties to decompress than you can use LzmaSDKObjCBufferDecompressLZMA2 function.

**Comment by sswain2** [comment]
hello ,

can i get some working examples of this library where i can see and debug the code for creating a 7z and extracting it .
if possible please share it in my email id - sandeepan.sw@gmail.com .

**Comment by OlehKulykov** [comment]
Hi,
check out 'tests' branch for iOS and MacOS Unit tests.

**Comment by OlehKulykov** [comment]
Hi,
yes you can, please refer to section "List and extract" in a README file or on the main page.
